
import { Property, Tenant, PropertyType, PropertyStatus } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 'prop1',
    name: 'The Grand Heights',
    address: '123 Main St, Metropolis, USA',
    type: PropertyType.Residential,
    size: 120000,
    amenities: ['Pool', 'Gym', 'Parking', 'Rooftop Lounge'],
    imageUrl: 'https://picsum.photos/seed/prop1/800/600',
    status: PropertyStatus.Occupied,
    units: 150,
  },
  {
    id: 'prop2',
    name: 'Commerce Tower',
    address: '456 Market Ave, Gotham City, USA',
    type: PropertyType.Commercial,
    size: 250000,
    amenities: ['Conference Rooms', 'Cafe', 'High-Speed Internet'],
    imageUrl: 'https://picsum.photos/seed/prop2/800/600',
    status: PropertyStatus.Occupied,
    units: 50,
  },
  {
    id: 'prop3',
    name: 'Oakwood Apartments',
    address: '789 Pine Ln, Star City, USA',
    type: PropertyType.Residential,
    size: 85000,
    amenities: ['Playground', 'Laundry Facilities', 'Pet Friendly'],
    imageUrl: 'https://picsum.photos/seed/prop3/800/600',
    status: PropertyStatus.Vacant,
    units: 100,
  },
  {
    id: 'prop4',
    name: 'Industrial Park West',
    address: '101 Factory Rd, Central City, USA',
    type: PropertyType.Industrial,
    size: 500000,
    amenities: ['Loading Docks', '24/7 Security', 'Large Vehicle Access'],
    imageUrl: 'https://picsum.photos/seed/prop4/800/600',
    status: PropertyStatus.UnderMaintenance,
    units: 10,
  },
  {
    id: 'prop5',
    name: 'The Lofts at Downtown',
    address: '212 River Walk, Coast City, USA',
    type: PropertyType.MixedUse,
    size: 180000,
    amenities: ['Retail Space', 'Residential Units', 'Shared Workspace'],
    imageUrl: 'https://picsum.photos/seed/prop5/800/600',
    status: PropertyStatus.Occupied,
    units: 80,
  },
  {
    id: 'prop6',
    name: 'Creekside Villas',
    address: '333 Willow Creek Dr, Smallville, USA',
    type: PropertyType.Residential,
    size: 95000,
    amenities: ['Garden', 'Community Hall', 'Walking Trails'],
    imageUrl: 'https://picsum.photos/seed/prop6/800/600',
    status: PropertyStatus.Vacant,
    units: 60,
  },
];

export const TENANTS: Tenant[] = [
  {
    id: 'ten1',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '555-0101',
    propertyId: 'prop1',
    unit: 'Apt 12B',
    leaseEndDate: '2025-08-31',
    moveInDate: '2023-09-01',
  },
  {
    id: 'ten2',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    phone: '555-0102',
    propertyId: 'prop1',
    unit: 'Apt 5C',
    leaseEndDate: '2024-12-31',
    moveInDate: '2023-01-01',
  },
  {
    id: 'ten3',
    name: 'Innovate Corp',
    email: 'contact@innovatecorp.com',
    phone: '555-0103',
    propertyId: 'prop2',
    unit: 'Suite 200',
    leaseEndDate: '2026-05-31',
    moveInDate: '2021-06-01',
  },
  {
    id: 'ten4',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    phone: '555-0104',
    propertyId: 'prop5',
    unit: 'Loft 3A',
    leaseEndDate: '2025-02-28',
    moveInDate: '2024-03-01',
  },
  {
    id: 'ten5',
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    phone: '555-0105',
    propertyId: 'prop1',
    unit: 'PH-1',
    leaseEndDate: '2025-11-30',
    moveInDate: '2022-12-01',
  },
    {
    id: 'ten6',
    name: 'Global Solutions Ltd.',
    email: 'hq@globalsolutions.com',
    phone: '555-0106',
    propertyId: 'prop2',
    unit: 'Suite 450',
    leaseEndDate: '2028-01-31',
    moveInDate: '2023-02-01',
  },
];
